[project]
name = "mcp-naturalfrequency"
version = "0.1.0"
description = "A tool for calculating the eigenfrequency of beams with different supports."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.7.1",
    "numpy>=2.2.5",
]
